name: Run Selenium Tests

on:
  push: # автоматический запуск
  workflow_dispatch: # ручной запуск
    inputs:
      test_suite:
        type: choice
        description: "Выберите набор тестов"
        required: true
        default: "changed"
        options:
          - all
          - changed
          - smoke
          - regression
          - ui
          - custom_path
          - custom_marker
      test_path:
        description: "Укажите путь к тестам (если выбран custom_path)"
        required: false
      test_marker:
        description: "Укажите pytest-маркер (если выбран custom_marker)"
        required: false

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
        workers: [4]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip xvfb libnss3 libgtk-3-0 libasound2t64
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt
          pip3 install pytest-xdist

      - name: Run selected tests
        run: |
          # если ручной запуск → берем inputs, если push → дефолт "changed"
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            TEST_SUITE="${{ github.event.inputs.test_suite }}"
            TEST_PATH="${{ github.event.inputs.test_path }}"
            TEST_MARKER="${{ github.event.inputs.test_marker }}"
          else
            TEST_SUITE="changed"
            TEST_PATH=""
            TEST_MARKER=""
          fi

          echo "Режим запуска: $TEST_SUITE"
          echo "Путь: $TEST_PATH"
          echo "Маркер: $TEST_MARKER"

          TEST_CMD="pytest -v -n ${{ matrix.workers }}"

          if [[ "$TEST_SUITE" == "all" ]]; then
              $TEST_CMD
          elif [[ "$TEST_SUITE" == "changed" ]]; then
              PREV_COMMIT=$(git rev-parse HEAD~1 2>/dev/null || echo "")
              if [ -n "$PREV_COMMIT" ]; then
                  CHANGED_TESTS=$(git diff --name-only $PREV_COMMIT ${{ github.sha }} | grep -E 'test/.*\.py$' || true)
              else
                  CHANGED_TESTS=""
              fi

              if [ -n "$CHANGED_TESTS" ]; then
                  echo "Изменённые тесты: $CHANGED_TESTS"
                  $TEST_CMD $CHANGED_TESTS
              else
                  echo "Изменённых тестов нет → гоняем все"
                  $TEST_CMD
              fi
          elif [[ "$TEST_SUITE" == "smoke" ]]; then
              $TEST_CMD -m "smoke"
          elif [[ "$TEST_SUITE" == "regression" ]]; then
              $TEST_CMD -m "regression"
          elif [[ "$TEST_SUITE" == "ui" ]]; then
              $TEST_CMD -m "ui"
          elif [[ "$TEST_SUITE" == "custom_path" ]]; then
              if [ -n "$TEST_PATH" ]; then
                  echo "Запуск по пути: $TEST_PATH"
                  $TEST_CMD "$TEST_PATH"
              else
                  echo "Ошибка: test_path пустой"
                  exit 1
              fi
          elif [[ "$TEST_SUITE" == "custom_marker" ]]; then
              if [ -n "$TEST_MARKER" ]; then
                  echo "Запуск по маркеру: $TEST_MARKER"
                  $TEST_CMD -m "$TEST_MARKER"
              else
                  echo "Ошибка: test_marker пустой"
                  exit 1
              fi
          else
              echo "Неизвестный вариант: $TEST_SUITE"
              exit 1
          fi
      